title: Lizzie's Blog
description: A website with a blog
footer_text: Copyright 2021 Lizzie Vascenko
header_feature_image: ../uploads/photo-1519682337058-a94d519337bc.jpg
header_text: Thoughts and Opinions
header_text_color: "#01095a"
bannerheight: 20vmax
logo: ../uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
