title: Lizzie's Blog
description: A website with a blog
footer_text: Copyright 2021 Lizzie Vascenko
header_feature_image: ../uploads/photo-1569705474611-051bf56f332c.jpg
header_text: Thoughts and Opinions
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: ../uploads/thumbnail-7-.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
